services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: private-markets-api-${CONTAINER_NAME:-dev}
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
